[bastion]
bastion.ru-central1.internal

[webservers]
web1.ru-central1.internal
web2.ru-central1.internal

[monitoring]
zabbix.ru-central1.internal

[logging]
elasticsearch.ru-central1.internal
kibana.ru-central1.internal

[zabbix_agents:children]
webservers
logging

[all:vars]
ansible_user=ubuntu