---
- name: Deploy Elasticsearch
  hosts: elasticsearch.ru-central1.internal
  become: yes
  roles:
    - elasticsearch

- name: Deploy Kibana
  hosts: kibana.ru-central1.internal
  become: yes
  roles:
    - kibana

- name: Deploy Filebeat on web servers
  hosts: webservers
  become: yes
  roles:
    - filebeat